export const {
	NEXT_PUBLIC_DEPLOYMENT,
	NEXT_PUBLIC_SDK_BASE_URL,
	POLKASAFE_FIREBASE_CONFIG,
	SUBSCAN_API_KEY,
	NEXT_PUBLIC_IMBB_KEY,
	NOTIFICATION_ENGINE_API_KEY,
	NOTIFICATION_SOURCE,
	POLKASAFE_FIREBASE_CONFIG_CLIENT
} = process.env;
